Repository topology-tool-kit/ttk, pull requests merged in 2020-02, with the labels that each got.

#330 Periodic triangulation switcher
  core/base/abstractTriangulation/AbstractTriangulation.cpp
  core/base/abstractTriangulation/AbstractTriangulation.h
  core/base/helloWorld/HelloWorld.h
  core/base/periodicImplicitTriangulation/PeriodicImplicitTriangulation.cpp
  core/base/scalarFieldCriticalPoints/ScalarFieldCriticalPoints.inl
  core/base/triangulation/Triangulation.cpp
  core/base/triangulation/Triangulation.h
  core/vtk/ttkAlgorithm/ttkAlgorithm.cpp
  core/vtk/ttkPeriodicGrid/CMakeLists.txt
  core/vtk/ttkPeriodicGrid/ttk.module
  core/vtk/ttkPeriodicGrid/ttkPeriodicGrid.cpp
  core/vtk/ttkPeriodicGrid/ttkPeriodicGrid.h
  core/vtk/ttkPeriodicGrid/vtk.module
  core/vtk/ttkTriangulationAlgorithm/macro.h
  paraview/BarycentricSubdivision/BarycentricSubdivision.xml
  paraview/ComponentSize/ComponentSize.xml
  paraview/DistanceField/DistanceField.xml
  paraview/GeometrySmoother/GeometrySmoother.xml
  paraview/ManifoldCheck/ManifoldCheck.xml
  paraview/MeshSubdivision/MeshSubdivision.xml
  paraview/PeriodicGrid/PeriodicGrid.xml
  paraview/PeriodicGrid/TTKFilter.cmake
  paraview/PointMerger/PointMerger.xml
  paraview/QuadrangulationSubdivision/QuadrangulationSubdivision.xml
  paraview/TriangulationRequest/TriangulationRequest.xml
Labels: enhancement, ready

#328 ready: quick version for GetVoidPointer
  core/vtk/CMakeLists.txt
  core/vtk/ttkAlgorithm/ttkAlgorithm.cpp
  core/vtk/ttkAlgorithm/ttkUtils.h
  core/vtk/ttkArrayEditor/ttkArrayEditor.cpp
  core/vtk/ttkBarycentricSubdivision/ttkBarycentricSubdivision.cpp
  core/vtk/ttkBlank/ttk.module
  core/vtk/ttkBlank/ttkBlank.cpp
  core/vtk/ttkCellDataConverter/ttk.module
  core/vtk/ttkCellDataConverter/ttkCellDataConverter.cpp
  core/vtk/ttkCinemaImaging/ttkCinemaImaging.cpp
  core/vtk/ttkContinuousScatterPlot/ttkContinuousScatterPlot.cpp
  core/vtk/ttkContourForests/ttkContourForests.cpp
  core/vtk/ttkDepthImageBasedGeometryApproximation/ttkDepthImageBasedGeometryApproximation.cpp
  core/vtk/ttkDimensionReduction/ttkDimensionReduction.cpp
  core/vtk/ttkExtract/ttkExtract.cpp
  core/vtk/ttkFTMTree/ttkFTMTree.cpp
  core/vtk/ttkIcoSphere/ttkIcoSphere.cpp
  core/vtk/ttkMorseSmaleQuadrangulation/ttkMorseSmaleQuadrangulation.cpp
  core/vtk/ttkQuadrangulationSubdivision/ttkQuadrangulationSubdivision.cpp
  core/vtk/ttkReebSpace/ttkReebSpace.cpp
  core/vtk/ttkTriangulationAlgorithm/ttk.module
  core/vtk/ttkTriangulationAlgorithm/ttkTriangulation.cpp
Labels: WIP, bug, enhancement

#323 Sanity checks for "ttkTriangulation from vtkUnstructuredGrid"
  .gitignore
  CMakeLists.txt
  core/vtk/ttkTriangulationAlgorithm/ttkTriangulation.cpp
Labels: WIP, enhancement
