Repository topology-tool-kit/ttk, pull requests merged in 2020-09, with the labels that each got.

#481 Support sorted offset fields
  core/base/abstractMorseSmaleComplex/AbstractMorseSmaleComplex.h
  core/base/common/CMakeLists.txt
  core/base/common/OrderDisambiguation.h
  core/base/discreteGradient/DiscreteGradient.h
  core/base/discreteGradient/DiscreteGradient_Template.h
  core/base/ftrGraph/FTRGraph.h
  core/base/ftrGraph/FTRGraph_Template.h
  core/base/ftrGraph/FTRScalars.h
  core/base/jacobiSet/JacobiSet_Template.h
  core/base/morseSmaleComplex2D/MorseSmaleComplex2D.h
  core/base/morseSmaleComplex3D/MorseSmaleComplex3D.h
  core/base/scalarFieldCriticalPoints/ScalarFieldCriticalPoints.cpp
  core/base/scalarFieldCriticalPoints/ScalarFieldCriticalPoints.h
  core/base/topologicalCompression/OtherCompression.h
  core/base/topologicalCompression/PersistenceDiagramCompression.h
  core/base/topologicalCompression/TopologicalCompression.h
  core/base/topologicalSimplification/TopologicalSimplification.h
  core/vtk/ttkAlgorithm/ttkAlgorithm.cpp
  core/vtk/ttkAlgorithm/ttkAlgorithm.h
  core/vtk/ttkAlgorithm/ttkMacros.h
  core/vtk/ttkArrayPreconditioning/CMakeLists.txt
  core/vtk/ttkArrayPreconditioning/ttk.module
  core/vtk/ttkArrayPreconditioning/ttkArrayPreconditioning.cpp
  core/vtk/ttkArrayPreconditioning/ttkArrayPreconditioning.h
  core/vtk/ttkArrayPreconditioning/vtk.module
  core/vtk/ttkContourForests/ttkContourForests.cpp
  core/vtk/ttkDiscreteGradient/ttkDiscreteGradient.cpp
  core/vtk/ttkFTMTree/ttkFTMTree.cpp
  core/vtk/ttkFTRGraph/ttkFTRGraph.cpp
  core/vtk/ttkFTRGraph/ttkFTRGraph.h
  core/vtk/ttkGeometrySmoother/ttkGeometrySmoother.cpp
  core/vtk/ttkHarmonicField/ttkHarmonicField.cpp
  core/vtk/ttkHelloWorld/ttkHelloWorld.cpp
  core/vtk/ttkIntegralLines/ttkIntegralLines.cpp
  core/vtk/ttkJacobiSet/ttkJacobiSet.cpp
  core/vtk/ttkMorseSmaleComplex/ttkMorseSmaleComplex.cpp
  core/vtk/ttkPersistenceCurve/ttkPersistenceCurve.cpp
  core/vtk/ttkPersistenceDiagram/ttkPersistenceDiagram.cpp
  core/vtk/ttkReebSpace/ttkReebSpace.cpp
  core/vtk/ttkScalarFieldCriticalPoints/ttkScalarFieldCriticalPoints.cpp
  core/vtk/ttkScalarFieldCriticalPoints/ttkScalarFieldCriticalPoints.h
  core/vtk/ttkScalarFieldSmoother/ttkScalarFieldSmoother.cpp
  core/vtk/ttkTopologicalCompression/ttkTopologicalCompression.cpp
  core/vtk/ttkTopologicalCompressionReader/ttkTopologicalCompressionReader.cpp
  core/vtk/ttkTopologicalCompressionWriter/ttkTopologicalCompressionWriter.cpp
  core/vtk/ttkTopologicalSimplification/ttkTopologicalSimplification.cpp
  core/vtk/ttkTopologicalSimplification/ttkTopologicalSimplification.h
  core/vtk/ttkTrackingFromFields/ttkTrackingFromFields.h
  paraview/ArrayPreconditioning/ArrayPreconditioning.xml
  paraview/ArrayPreconditioning/TTKFilter.cmake
  paraview/TopologicalSimplification/TopologicalSimplification.xml
  paraview/patch/data/Example1.pvsm
  paraview/patch/data/Example3.pvsm
Labels: WIP

#485 ContourTreeAlignment Migration from TUKL repository
  core/base/contourTreeAlignment/CMakeLists.txt
  core/base/contourTreeAlignment/ContourTreeAlignment.cpp
  core/base/contourTreeAlignment/ContourTreeAlignment.h
  core/base/contourTreeAlignment/contourtree.cpp
  core/base/contourTreeAlignment/contourtree.h
  core/vtk/ttkContourTreeAlignment/CMakeLists.txt
  core/vtk/ttkContourTreeAlignment/ttk.module
  core/vtk/ttkContourTreeAlignment/ttkContourTreeAlignment.cpp
  core/vtk/ttkContourTreeAlignment/ttkContourTreeAlignment.h
  core/vtk/ttkContourTreeAlignment/vtk.module
  paraview/ContourTreeAlignment/ContourTreeAlignment.xml
  paraview/ContourTreeAlignment/TTKFilter.cmake
Labels: discussion

#495 Remove linking against all VTK_LIBRARIES
  CMake/VTKModule.cmake
  core/vtk/ttkCinemaImaging/vtk.module
  core/vtk/ttkCinemaProductReader/vtk.module
  core/vtk/ttkCinemaQuery/vtk.module
  core/vtk/ttkCinemaReader/vtk.module
  core/vtk/ttkCinemaWriter/vtk.module
  core/vtk/ttkContourForests/vtk.module
  core/vtk/ttkHelloWorld/ttkHelloWorld.h
  core/vtk/ttkMeshGraph/vtk.module
  core/vtk/ttkProgramBase/vtk.module
  core/vtk/ttkRangePolygon/vtk.module
  core/vtk/ttkSphereFromPoint/vtk.module
  core/vtk/ttkUserInterfaceBase/vtk.module
  core/vtk/ttkWRLExporter/vtk.module
  standalone/ContinuousScatterPlot/CMakeLists.txt
  standalone/ContourAroundPoint/CMakeLists.txt
  standalone/ContourForests/CMakeLists.txt
  standalone/FTMTree/CMakeLists.txt
  standalone/FTRGraph/CMakeLists.txt
  standalone/HelloWorld/CMakeLists.txt
  standalone/JacobiSet/CMakeLists.txt
  standalone/LDistance/CMakeLists.txt
  standalone/MandatoryCriticalPoints/CMakeLists.txt
  standalone/ManifoldCheck/CMakeLists.txt
  standalone/MeshSubdivision/CMakeLists.txt
  standalone/MorseSmaleComplex/CMakeLists.txt
  standalone/PersistenceDiagram/CMakeLists.txt
  standalone/PointMerger/CMakeLists.txt
  standalone/ReebSpace/CMakeLists.txt
  standalone/ScalarFieldCriticalPoints/CMakeLists.txt
  standalone/ScalarFieldSmoother/CMakeLists.txt
  standalone/UncertainDataEstimator/CMakeLists.txt
Labels: WIP, needTesting

#498 LTS Module
  azure-pipelines.yml
  core/base/localizedTopologicalSimplification/CMakeLists.txt
  core/base/localizedTopologicalSimplification/LocalizedTopologicalSimplification.cpp
  core/base/localizedTopologicalSimplification/LocalizedTopologicalSimplification.h
  core/base/localizedTopologicalSimplification/SSCPropagation.h
  core/base/topologicalSimplification/TopologicalSimplification.h
  core/vtk/ttkTopologicalSimplification/ttk.module
  core/vtk/ttkTopologicalSimplification/ttkTopologicalSimplification.cpp
  core/vtk/ttkTopologicalSimplification/ttkTopologicalSimplification.h
  paraview/TopologicalSimplification/TopologicalSimplification.xml
Labels: WIP, needTesting
