Repository topology-tool-kit/ttk, pull requests merged in 2020-07, with the labels that each got.

#399 [api-migration-hackathon] ttkIntegralLines
  core/base/integralLines/IntegralLines.cpp
  core/base/integralLines/IntegralLines.h
  core/vtk/ttkIntegralLines/ttk.module
  core/vtk/ttkIntegralLines/ttkIntegralLines.cpp
  core/vtk/ttkIntegralLines/ttkIntegralLines.h
  core/vtk/ttkIntegralLines/vtk.module
  paraview/IntegralLines/IntegralLines.xml
Labels: ready

#401 [api-migration-hackathon] ttkScalarFieldSmoother
  core/base/scalarFieldSmoother/ScalarFieldSmoother.cpp
  core/base/scalarFieldSmoother/ScalarFieldSmoother.h
  core/vtk/ttkGeometrySmoother/ttkGeometrySmoother.cpp
  core/vtk/ttkRangePolygon/ttkRangePolygon.cpp
  core/vtk/ttkScalarFieldSmoother/ttk.module
  core/vtk/ttkScalarFieldSmoother/ttkScalarFieldSmoother.cpp
  core/vtk/ttkScalarFieldSmoother/ttkScalarFieldSmoother.h
  core/vtk/ttkScalarFieldSmoother/vtk.module
  paraview/ScalarFieldSmoother/ScalarFieldSmoother.xml
  standalone/GeometrySmoother/cmd/main.cpp
  standalone/ScalarFieldSmoother/CMakeLists.txt
  standalone/ScalarFieldSmoother/cmd/main.cpp
  standalone/ScalarFieldSmoother/main.cpp
Labels: ready

#405 [api-migration-hackathon] ttkAlgorithm and ttk::ExplicitTriangulation now validate input cells …
  core/base/explicitTriangulation/ExplicitTriangulation.h
  core/vtk/ttkAlgorithm/ttkAlgorithm.cpp
  core/vtk/ttkAlgorithm/ttkAlgorithm.h
Labels: discussion

#406 [api-migration-hackathon] Identify by scalar field migration
  core/vtk/ttkIdentifyByScalarField/ttk.module
  core/vtk/ttkIdentifyByScalarField/ttkIdentifyByScalarField.cpp
  core/vtk/ttkIdentifyByScalarField/ttkIdentifyByScalarField.h
  core/vtk/ttkIdentifyByScalarField/vtk.module
  paraview/IdentifyByScalarField/IdentifyByScalarField.xml
Labels: ready

#408 [api-migration-hackathon] PersistenceDiagramClustering
  core/base/auction/Auction.h
  core/base/persistenceDiagramClustering/PDBarycenter.h
  core/base/persistenceDiagramClustering/PDBarycenterImpl.h
  core/base/persistenceDiagramClustering/PDClustering.h
  core/base/persistenceDiagramClustering/PDClusteringImpl.h
  core/base/persistenceDiagramClustering/PersistenceDiagramBarycenter.h
  core/base/persistenceDiagramClustering/PersistenceDiagramClustering.h
  core/vtk/ttkPersistenceDiagramClustering/ttk.module
  core/vtk/ttkPersistenceDiagramClustering/ttkPersistenceDiagramClustering.cpp
  core/vtk/ttkPersistenceDiagramClustering/ttkPersistenceDiagramClustering.h
  core/vtk/ttkPersistenceDiagramClustering/vtk.module
  paraview/PersistenceDiagramClustering/PersistenceDiagramClustering.xml
  standalone/PersistenceDiagramClustering/cmd/CMakeLists.txt
  standalone/PersistenceDiagramClustering/cmd/main.cpp
  standalone/PersistenceDiagramClustering/gui/CMakeLists.txt
  standalone/PersistenceDiagramClustering/gui/main.cpp
Labels: ready

#402 [api-migration-hackathon] MorseSmaleQuadrangulation + BarycentricSubdivision + QuadrangulationSubdivision (+Dijkstra)
  core/base/barycentricSubdivision/BarycentricSubdivision.cpp
  core/base/barycentricSubdivision/BarycentricSubdivision.h
  core/base/dijkstra/CMakeLists.txt
  core/base/dijkstra/Dijkstra.cpp
  core/base/dijkstra/Dijkstra.h
  core/base/morseSmaleQuadrangulation/MorseSmaleQuadrangulation.cpp
  core/base/morseSmaleQuadrangulation/MorseSmaleQuadrangulation.h
  core/base/quadrangulationSubdivision/QuadrangulationSubdivision.cpp
  core/base/quadrangulationSubdivision/QuadrangulationSubdivision.h
  core/vtk/ttkBarycentricSubdivision/ttk.module
  core/vtk/ttkBarycentricSubdivision/ttkBarycentricSubdivision.cpp
  core/vtk/ttkBarycentricSubdivision/ttkBarycentricSubdivision.h
  core/vtk/ttkBarycentricSubdivision/vtk.module
  core/vtk/ttkMorseSmaleQuadrangulation/ttk.module
  core/vtk/ttkMorseSmaleQuadrangulation/ttkMorseSmaleQuadrangulation.cpp
  core/vtk/ttkMorseSmaleQuadrangulation/ttkMorseSmaleQuadrangulation.h
  core/vtk/ttkMorseSmaleQuadrangulation/vtk.module
  core/vtk/ttkQuadrangulationSubdivision/ttk.module
  core/vtk/ttkQuadrangulationSubdivision/ttkQuadrangulationSubdivision.cpp
  core/vtk/ttkQuadrangulationSubdivision/ttkQuadrangulationSubdivision.h
  core/vtk/ttkQuadrangulationSubdivision/vtk.module
  paraview/BarycentricSubdivision/BarycentricSubdivision.xml
  paraview/MorseSmaleQuadrangulation/MorseSmaleQuadrangulation.xml
  paraview/QuadrangulationSubdivision/QuadrangulationSubdivision.xml
Labels: ready

#417 [api-migration-hackathon] ttkIdentifierRandomizer
  core/vtk/ttkIdentifierRandomizer/ttk.module
  core/vtk/ttkIdentifierRandomizer/ttkIdentifierRandomizer.cpp
  core/vtk/ttkIdentifierRandomizer/ttkIdentifierRandomizer.h
  core/vtk/ttkIdentifierRandomizer/vtk.module
  paraview/IdentifierRandomizer/IdentifierRandomizer.xml
Labels: ready

#419 [api-migration-hackathon] ttkSphereFromPoint
  core/vtk/ttkIdentifiers/ttkIdentifiers.cpp
  core/vtk/ttkSphereFromPoint/ttk.module
  core/vtk/ttkSphereFromPoint/ttkSphereFromPoint.cpp
  core/vtk/ttkSphereFromPoint/ttkSphereFromPoint.h
  core/vtk/ttkSphereFromPoint/vtk.module
  paraview/SphereFromPoint/SphereFromPoint.xml
Labels: ready

#415 [api-migration-hackathon] Periodic grid switcher
  core/vtk/ttkPeriodicGrid/ttk.module
  core/vtk/ttkPeriodicGrid/ttkPeriodicGrid.cpp
  core/vtk/ttkPeriodicGrid/ttkPeriodicGrid.h
Labels: ready

#420 [api-migration-hackathon] New data array management for PointSetToCurve, StringArrayConverter & LDistanteMatrix
  core/vtk/ttkLDistanceMatrix/ttkLDistanceMatrix.cpp
  core/vtk/ttkLDistanceMatrix/ttkLDistanceMatrix.h
  core/vtk/ttkPointSetToCurve/ttkPointSetToCurve.cpp
  core/vtk/ttkPointSetToCurve/ttkPointSetToCurve.h
  core/vtk/ttkStringArrayConverter/ttkStringArrayConverter.cpp
  core/vtk/ttkStringArrayConverter/ttkStringArrayConverter.h
  paraview/LDistanceMatrix/LDistanceMatrix.xml
  paraview/PointSetToCurve/PointSetToCurve.xml
  paraview/StringArrayConverter/StringArrayConverter.xml
Labels: ready

#422 [api-migration-hackathon] ttkRangePolygon
  core/vtk/ttkRangePolygon/ttk.module
  core/vtk/ttkRangePolygon/ttkRangePolygon.cpp
  core/vtk/ttkRangePolygon/ttkRangePolygon.h
  core/vtk/ttkRangePolygon/vtk.module
Labels: ready

#425 [api-migration-hackathon] ttkProjectionFromField
  core/vtk/ttkProjectionFromField/ttk.module
  core/vtk/ttkProjectionFromField/ttkProjectionFromField.cpp
  core/vtk/ttkProjectionFromField/ttkProjectionFromField.h
  core/vtk/ttkProjectionFromField/vtk.module
  paraview/ProjectionFromField/ProjectionFromField.xml
Labels: ready

#423 [api-migration-hackathon] Tracking from overlap migration
  core/base/trackingFromOverlap/TrackingFromOverlap.h
  core/vtk/ttkTrackingFromOverlap/ttk.module
  core/vtk/ttkTrackingFromOverlap/ttkTrackingFromOverlap.cpp
  core/vtk/ttkTrackingFromOverlap/ttkTrackingFromOverlap.h
  core/vtk/ttkTrackingFromOverlap/vtk.module
  paraview/TrackingFromOverlap/TrackingFromOverlap.xml
Labels: ready

#410 [api-migration-hackathon] PersistenceCurve Migration
  core/base/persistenceCurve/PersistenceCurve.cpp
  core/base/persistenceCurve/PersistenceCurve.h
  core/vtk/ttkPersistenceCurve/ttk.module
  core/vtk/ttkPersistenceCurve/ttkPersistenceCurve.cpp
  core/vtk/ttkPersistenceCurve/ttkPersistenceCurve.h
  core/vtk/ttkPersistenceCurve/vtk.module
  paraview/PersistenceCurve/PersistenceCurve.xml
Labels: WIP, needTesting

#421 [api-migration-hackathon] ttkContinuousScatterPlot
  core/base/continuousScatterPlot/ContinuousScatterPlot.cpp
  core/base/continuousScatterPlot/ContinuousScatterPlot.h
  core/vtk/ttkContinuousScatterPlot/ttk.module
  core/vtk/ttkContinuousScatterPlot/ttkContinuousScatterPlot.cpp
  core/vtk/ttkContinuousScatterPlot/ttkContinuousScatterPlot.h
  core/vtk/ttkContinuousScatterPlot/vtk.module
  paraview/ContinuousScatterPlot/ContinuousScatterPlot.xml
  standalone/ContinuousScatterPlot/CMakeLists.txt
  standalone/ContinuousScatterPlot/cmd/main.cpp
  standalone/ContinuousScatterPlot/main.cpp
Labels: needTesting, ready

#430 [api-migration-hackathon] ttkDataSetInterpolator migration
  core/vtk/ttkDataSetInterpolator/CMakeLists.txt
  core/vtk/ttkDataSetInterpolator/ttk.module
  core/vtk/ttkDataSetInterpolator/ttkDataSetInterpolator.cpp
  core/vtk/ttkDataSetInterpolator/ttkDataSetInterpolator.h
  core/vtk/ttkDataSetInterpolator/vtk.module
  paraview/DataSetInterpolator/DataSetInterpolator.xml
Labels: ready

#429 [api-migration-hackathon] ttkComponentSize
  core/vtk/ttkComponentSize/CMakeLists.txt
  core/vtk/ttkComponentSize/ttk.module
  core/vtk/ttkComponentSize/ttkComponentSize.cpp
  core/vtk/ttkComponentSize/ttkComponentSize.h
  core/vtk/ttkComponentSize/vtk.module
  paraview/ComponentSize/ComponentSize.xml
  paraview/ComponentSize/TTKFilter.cmake
Labels: ready

#431 [api-migration-hackathon] ttkDataSetToTable
  core/vtk/ttkDataSetToTable/CMakeLists.txt
  core/vtk/ttkDataSetToTable/ttk.module
  core/vtk/ttkDataSetToTable/ttkDataSetToTable.cpp
  core/vtk/ttkDataSetToTable/ttkDataSetToTable.h
  core/vtk/ttkDataSetToTable/vtk.module
  paraview/DataSetToTable/DataSetToTable.xml
Labels: ready

#436 Bug fix: `make install` for ParaView plugins
  CMake/ParaViewFilter.cmake
  CMake/VTKModule.cmake
  config.cmake
  paraview/singlePlugin/CMakeLists.txt
Labels: ready

#434 Cmake
  CMake/ParaViewFilter.cmake
  CMakeLists.txt
Labels: WIP, discussion

#433 [api-migration-hackathon] Contour around point
  core/base/auction/AuctionActor.h
  core/base/bottleneckDistance/BottleneckDistanceMainImpl.h
  core/base/contourAroundPoint/ContourAroundPoint.cpp
  core/base/contourAroundPoint/ContourAroundPoint.hpp
  core/base/contourForests/ContourForests.cpp
  core/base/depthImageBasedGeometryApproximation/DepthImageBasedGeometryApproximation.h
  core/base/lowestCommonAncestor/LowestCommonAncestor.cpp
  core/base/morseSmaleQuadrangulation/MorseSmaleQuadrangulation.h
  core/base/persistenceDiagramClustering/PDBarycenterImpl.h
  core/base/scalarFieldCriticalPoints/ScalarFieldCriticalPoints.h
  core/base/topologicalCompression/TopologicalCompression.h
  core/vtk/ttkAlgorithm/ttkAlgorithm.cpp
  core/vtk/ttkContourAroundPoint/ttk.module
  core/vtk/ttkContourAroundPoint/ttkContourAroundPoint.cpp
  core/vtk/ttkContourAroundPoint/ttkContourAroundPoint.h
  core/vtk/ttkContourAroundPoint/vtk.module
  core/vtk/ttkImportEmbeddingFromTable/ttkImportEmbeddingFromTable.cpp
  core/vtk/ttkMandatoryCriticalPoints/ttkMandatoryCriticalPoints.cpp
  paraview/ContourAroundPoint/ContourAroundPoint.xml
  standalone/ContourAroundPoint/CMakeLists.txt
  standalone/ContourAroundPoint/cmd/main.cpp
  standalone/ContourAroundPoint/gui/CMakeLists.txt
  standalone/ContourAroundPoint/gui/main.cpp
  standalone/ContourAroundPoint/main.cpp
Labels: WIP, needTesting

#428 [api-migration-hackathon] PersistenceDiagram migration
  core/base/persistenceDiagram/PersistenceDiagram.cpp
  core/base/persistenceDiagram/PersistenceDiagram.h
  core/base/trackingFromFields/TrackingFromFields.h
  core/vtk/ttkPersistenceCurve/ttkPersistenceCurve.cpp
  core/vtk/ttkPersistenceCurve/ttkPersistenceCurve.h
  core/vtk/ttkPersistenceDiagram/ttk.module
  core/vtk/ttkPersistenceDiagram/ttkPersistenceDiagram.cpp
  core/vtk/ttkPersistenceDiagram/ttkPersistenceDiagram.h
  core/vtk/ttkPersistenceDiagram/vtk.module
  paraview/PersistenceDiagram/PersistenceDiagram.xml
  standalone/PersistenceDiagram/CMakeLists.txt
  standalone/PersistenceDiagram/cmd/CMakeLists.txt
  standalone/PersistenceDiagram/cmd/main.cpp
  standalone/PersistenceDiagram/gui/main.cpp
  standalone/PersistenceDiagram/main.cpp
Labels: WIP, bug, needTesting

#437 [api-migration-hackathon] TopologicalCompression
  CMake/topological_compression.xml
  core/base/topologicalCompression/OtherCompression.h
  core/base/topologicalCompression/PersistenceDiagramCompression.h
  core/base/topologicalCompression/TopologicalCompression.cpp
  core/base/topologicalCompression/TopologicalCompression.h
  core/base/topologicalSimplification/TopologicalSimplification.h
  core/vtk/ttkCinemaProductReader/ttkCinemaProductReader.cpp
  core/vtk/ttkCinemaWriter/ttkCinemaWriter.cpp
  core/vtk/ttkCinemaWriter/ttkCinemaWriter.h
  core/vtk/ttkTopologicalCompression/ttk.module
  core/vtk/ttkTopologicalCompression/ttkTopologicalCompression.cpp
  core/vtk/ttkTopologicalCompression/ttkTopologicalCompression.h
  core/vtk/ttkTopologicalCompression/vtk.module
  core/vtk/ttkTopologicalCompressionReader/ttk.module
  core/vtk/ttkTopologicalCompressionReader/ttkTopologicalCompressionReader.cpp
  core/vtk/ttkTopologicalCompressionReader/ttkTopologicalCompressionReader.h
  core/vtk/ttkTopologicalCompressionReader/vtk.module
  core/vtk/ttkTopologicalCompressionWriter/ttk.module
  core/vtk/ttkTopologicalCompressionWriter/ttkTopologicalCompressionWriter.cpp
  core/vtk/ttkTopologicalCompressionWriter/ttkTopologicalCompressionWriter.h
  core/vtk/ttkTopologicalCompressionWriter/vtk.module
  paraview/CinemaWriter/CinemaWriter.xml
  paraview/TopologicalCompression/TopologicalCompression.xml
  paraview/TopologicalCompressionWriter/TopologicalCompressionWriter.xml
Labels: WIP, needTesting

#450 Add missing depends and fix RPATH
  config.cmake
  core/vtk/ttkCinemaImaging/vtk.module
  core/vtk/ttkUserInterfaceBase/vtk.module
Labels: ready
