Repository topology-tool-kit/ttk, pull requests merged in 2022-05, with the labels that each got.

#769 Fix some memory-related issues
  core/base/abstractTriangulation/AbstractTriangulation.h
  core/base/common/CMakeLists.txt
  core/base/common/Cache.h
  core/base/continuousScatterPlot/ContinuousScatterPlot.h
  core/base/discreteGradient/DiscreteGradient_Template.h
  core/base/fiberSurface/FiberSurface.cpp
  core/base/fiberSurface/FiberSurface.h
  core/base/geometry/Geometry.cpp
  core/base/geometry/Geometry.h
  core/base/jacobiSet/JacobiSet_Template.h
  core/base/rangeDrivenOctree/RangeDrivenOctree.cpp
  core/base/rangeDrivenOctree/RangeDrivenOctree.h
  core/base/reebSpace/ReebSpace.h
  standalone/ContinuousScatterPlot/main.cpp
  standalone/ContourAroundPoint/main.cpp
  standalone/ContourForests/main.cpp
  standalone/FTMTree/main.cpp
  standalone/FTRGraph/main.cpp
  standalone/HelloWorld/main.cpp
  standalone/JacobiSet/main.cpp
  standalone/LDistance/main.cpp
  standalone/MandatoryCriticalPoints/main.cpp
  standalone/ManifoldCheck/main.cpp
  standalone/MeshSubdivision/main.cpp
  standalone/MetricDistortion/main.cpp
  standalone/MorseSmaleComplex/main.cpp
  standalone/PersistenceDiagram/main.cpp
  standalone/PointMerger/main.cpp
  standalone/ReebSpace/main.cpp
  standalone/ScalarFieldCriticalPoints/main.cpp
  standalone/ScalarFieldSmoother/main.cpp
Labels: discussion

#772 [MPI] Fixes and Optimization for ArrayPreconditioning, more functionality for BaseMPIClass
  core/base/arrayPreconditioning/ArrayPreconditioning.h
  core/base/common/MPIUtils.h
  core/vtk/ttkArrayPreconditioning/ttkArrayPreconditioning.cpp
  paraview/patch/paraview-5.10.1-CMakeLists.txt.patch
  paraview/xmls/ArrayPreconditioning.xml
  paraview/xmls/MergeTreeClustering.xml
  paraview/xmls/MergeTreeDistanceMatrix.xml
Labels: conflict

#775 Docker Workflow Fix
  .github/workflows/README.md
  .github/workflows/docker.yml
Labels: enhancement, discussion
